schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - main

jobs:
- job: build_container
  steps:
    - bash: packer build -var github_feed_token="${{ github_feed_token }}" ubuntu2004-docker.json
